dataset: CUB200
first_split_size: 20
other_split_size: 20
schedule:
- 18
schedule_type: cosine
batch_size: 64
optimizer: Adam
momentum: 0.90
weight_decay: 0
model_type: zoo
model_name: vit_pt_imnet
max_task: -1
dataroot: data
workers: 4
validation: False
train_aug: True
rand_split: True